### ISSUE TITLE
Gradle and lwjgl 3.2.2-SNAPSHOT

### ISSUE THREAD

**Issue by Avantgarde95** [kotlin-graphics/glm#10]
I'm using your library in my project. My project's `build.gradle` originally looked like:
```
blahblah...

ext {
    ...
    glmVersion = 'v0.9.9.0-build-13'
}

repositories {
    jcenter()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    ...
    implementation "com.github.kotlin-graphics.glm:glm:$glmVersion"
}
```
Then when I run `gradlew build` or `gradlew run`, gradle fails to download lwjgl and emits an error that it can't find `3.2.2-SNAPSHOT` version of lwjgl. After reading your library's `build.gradle`, I found that you are using `oss.sonatype.org` for downloading lwjgl. So I added that repository to my project's `build.gradle` like the following code:
```
repositories {
    jcenter()
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```
And gradle works well now.

So I think that you should mention in `README.md` that the users should try this method if gradle emits lwjgl dependency error.

Thanks.

**Comment by elect86** [comment]
Fair point, thanks
