### ISSUE TITLE
Incorrect gradle linking example

### ISSUE THREAD

**Issue by asimaranov** [kotlin-graphics/glm#12]
The gradle linking example
```
dependencies {
      implementation 'com.github.kotlin-graphics.glm:glm:<version>'
  }
```
seems to be incorrect. Only such option- ```com.github.kotlin-graphics:glm:<version>``` worked for me

**Comment by elect86** [comment]
Weird, it works flawless on other projects (like [here](https://github.com/kotlin-graphics/imgui/blob/master/imgui-gl/build.gradle#L14))

Theoretically that should download all the modules availables (which for glm is not a problem since there are only 2 and one is essentially dummy)

**Comment by IRus** [comment]
I believe you looking at version 1.0.1 which 2 years old, and indeed has such `com.github.kotlin-graphics:glm:<version>` maven coordinates, relevant build file: https://github.com/kotlin-graphics/glm/blob/v1.0.1/build.gradle#L6

In master `.glm` suffix exists: https://github.com/kotlin-graphics/glm/blob/master/build.gradle#L27

**Comment by IRus** [comment]
https://github.com/kotlin-graphics/glm/wiki/1.-Getting-started#-11-setup - maven coordinates not quite right, `.glm` suffix if missing

**Comment by elect86** [comment]
This shall be fixed by now
