### ISSUE TITLE
NoSuchMethodError Vector

### ISSUE THREAD

**Issue by Mitti30** [kotlin-graphics/glm#17]
When trying to use the get() function of the Vec2i a NoSuchMethodError gets thrown.
When calling them directly a NoSuchFieldError appears.

`    private val creator=LevelCreator(Game.resolution[0].toFloat(), Game.resolution[1].toFloat(),14,8,0f,0f)`

https://github.com/Mitti30/BreakoutOpenGL

**Comment by elect86** [comment]
Hi Mitti,

was it fixed?

**Comment by Mitti30** [comment]
Yeah, i changed the gradle glm version to 
` implementation 'com.github.kotlin-graphics:glm:v0.9.9.1-build-3'`
previous used version was 
`  implementation 'com.github.kotlin-graphics:glm:v1.0.1'`
