### ISSUE TITLE
Unfriendly installation docs

### ISSUE THREAD

**Issue by cubuspl42** [kotlin-graphics/glm#19]
First, I'd like to thank you for creating a port of glm. I'd love to use it in my project and I'm very glad that you've put an effort to create this pure-Kotlin port.

Would you consider improving the documentation about getting the library? In my experience, picking a library looks like this: first I verify if this is the library I'm looking for, then I copy the Gradle snippet, typically from the top of the readme. In case of `kotlin-graphics/glm`, there's only a link pointing to `kotlin-graphics/mary`'s readme, which is some kind of an analysis, which is not really helpful for people who look for three magical lines of Gradle script (which is, 95% of people).

**Comment by elect86** [comment]
Hello cubuspl42,

first of all, sorry for the late reply

Sure, I'll add a code snippet to add the [mary](https://github.com/kotlin-graphics/mary) repository and add `glm` dependency

**Comment by Bixilon** [comment]
@cubuspl42 It is now properly published to maven central. You can get it with `dependencies { implementation 'io.github.kotlin-graphics:glm:0.9.9.1-12' }` .


Is this now user (developer?) friendly?
