### ISSUE TITLE
Docs don't mention it's a JVM-only project

### ISSUE THREAD

**Issue by cubuspl42** [kotlin-graphics/glm#20]
I was quite excited to give this project a try in my small Kotlin/JS + WebGL side-project and I discovered very late that it depends on `java.*` APIs. 

I'm aware of issue #6, but an important first step before implementing multiplatform support, in my opinion, could be mentioning current state in the readme clearly.

**Comment by elect86** [comment]
Hey,

sorry for the late reply, but I'm currently working on it, you can read all in #6

**Comment by elect86** [comment]
Hey, 

I just pushed the `mp` branch for the multiplatform

it's still in WIP but it should be already usable

**Comment by cubuspl42** [comment]
@elect86 Cool! I'll check it out when I have a free moment. I can't promise when that is, sadly 😞
