### ISSUE TITLE
How to use this with gradle

### ISSUE THREAD

**Issue by 06needhamt** [kotlin-graphics/glm#3]
Hi 

I would like to use this library within a gradle project but I am not sure how to add it to my build.gradle

Thanks in Advance

**Comment by elect86** [comment]
Ok, readme modified, you can either click there or [here](https://jitpack.io/#kotlin-graphics/glm/0.01)

**Comment by elect86** [comment]
allprojects {
		repositories {
			maven { url 'https://jitpack.io' }
		}
	}

     dependencies {
	        compile 'com.github.kotlin-graphics:glm:0.01'
	}
