### ISSUE TITLE
cannot not find class

### ISSUE THREAD

**Issue by bupt-he** [kotlin-graphics/glm#42]
Caused by: java.lang.ClassNotFoundException: Didn't find class "kool.ExtensionsKt" on path: DexPathList[[dex file "/data/data/com.example.opengl/code_cache/.overlay/base.apk/classes10.dex"

**Comment by Bixilon** [comment]
What did you try?

If you need kool, please add i too: see  https://github.com/kotlin-graphics/kool

**Comment by bupt-he** [comment]
![image](https://github.com/kotlin-graphics/glm/assets/59814713/ca75c928-0515-4928-8ec6-e95a35e1c8db)
![image](https://github.com/kotlin-graphics/glm/assets/59814713/84e73693-2c88-454f-badb-8273386c158b)
i use mat4.to(floatbuffer) ,it show the error in second picture.   the lib is  implementation("io.github.kotlin-graphics:glm:0.9.9.1-12")

**Comment by Bixilon** [comment]
yes, if you want to use it with buffers, you must add kool to your dependencies. See the readme I linked above
